### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by johnh03** [Sobremesa-Video/Sobremesa#14]
After we have a name that we want the website/project to be called, we should have a logo to represent our website.

**Comment by sherryh13** [comment]
I agree, I worked on the project a little bit tonight and I just put a random S icon on the webpage right now.

**Comment by johnh03** [comment]
I just checked it out, looks great along with the first page with Sign Up and Login. Once we build the video player, I was thinking of having the logo present in the top left corner sorta like the youtube logo. But I do think we can refine the logo at a later time since we don't really have a color theme decided for our project.

**Comment by sherryh13** [comment]
Logo Finalized by Ariel
